## Z-Test

In [1]:
import numpy as np
from scipy.stats import norm
from scipy import stats

In [2]:
sample = [172,174,168,169,171,173,175,170,169,172]
population_mean = 170
population_std = 3
sample_mean = np.mean(sample)
n = len(sample)

In [3]:
z_score = (sample_mean-population_mean)/(population_std/np.sqrt(n))
z_score

np.float64(1.3703203194063098)

In [4]:
p_value = 2*(1-norm.cdf(abs(z_score)))
p_value

np.float64(0.17058693287143756)

In [5]:
alpha = 0.05
if p_value < alpha:
    print("Null hypothesis rejected")
else:
    print("Null hypothesis accepted")

Null hypothesis accepted

## T-Test

In [6]:
#sample and sample mean we alr have
#but we need sample std now not population std
sample_std = np.std(sample, ddof=1) #degree of freedom

In [7]:
t_stats = (sample_mean - population_mean)/(sample_std/np.sqrt(n))
t_stats

np.float64(1.7782469350914734)

In [8]:
p_value_1 = 2*(1-stats.t.cdf(abs(t_stats), df=n-1))
alpha=0.05
p_value_1

np.float64(0.10907771593031335)

In [9]:
if p_value_1 < alpha:
    print("Null hypothesis rejected")
else:
    print("Null hypothesis accepted")

Null hypothesis accepted

## Two Sample Test

In [ ]:
boys = [85,88,90,92,87,85,89,91,86,88]
girls = [82,84,80,83,81,79,78,85,84,83]
#Null Hypo - No difference
#Alternate Hypo - Significant difference b/w performance

In [12]:
t_stats_1, p_value_2 = stats.ttest_ind(boys, girls, equal_var=False)
print(t_stats_1)
print(p_value_2)

5.829604009507161
1.61047559896588e-05

In [13]:
if p_value_2 < alpha:
    print("Null hypothesis rejected")
else:
    print("Null hypothesis accepted")

Null hypothesis rejected

## Chi Test

In [21]:
import seaborn as sns
from scipy.stats import chi2_contingency
import pandas as pd

In [20]:
df = sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [22]:
contigency_table = pd.crosstab(df['sex'], df['survived'])
contigency_table

survived    0    1
sex
female     81  233
male      468  109

In [24]:
chi2, p_value_3 , dof, expected = chi2_contingency(contigency_table)
print(chi2)
print(p_value_3)
print(dof)
print(expected)

260.71702016732104
1.1973570627755645e-58
1
[[193.47474747 120.52525253]
 [355.52525253 221.47474747]]

In [46]:
if p_value_3 < alpha:
    print("Null hypothesis rejected - There is a significant difference")
else:
    print("Null hypothesis accepted - There is no difference")

Null hypothesis rejected - There is a significant difference

## Annova Test

Analysis of Variance - used to compare means of more than two independent groups to check if at least one group mean is significantly different

E.g - "Do different teaching methods result in different average scores?"

In [28]:
from scipy.stats import f_oneway

In [36]:
df1 = sns.load_dataset('titanic')
df1
#we want to check if theres any relation b/w age and passenger class

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [39]:
df1 = df1[['pclass', 'age']].dropna()

In [ ]:
df1['pclass'].unique()

array([3, 1, 2])

In [43]:
class_1 = df1[df1['pclass']==1]['age']
class_2 = df1[df1['pclass']==2]['age']
class_3 = df1[df1['pclass']==3]['age']
class_1

1      38.0
3      35.0
6      54.0
11     58.0
23     28.0
       ...
871    47.0
872    33.0
879    56.0
887    19.0
889    26.0
Name: age, Length: 186, dtype: float64

In [44]:
f_stats , p_value_4 = f_oneway(class_1, class_2, class_3)
print(f_stats)
print(p_value_4)

57.44348434067624
7.487984171957403e-24

In [45]:
if p_value_4 < alpha:
    print("Null hypothesis rejected - There is a significant difference")
else:
    print("Null hypothesis accepted - There is no difference")

Null hypothesis rejected - There is a significant difference