In [2]:
import time
from rich.console import Console
import ipywidgets as widgets


def do_something_important():
    time.sleep(5.0)  # Simulates a long process

console = Console()
with console.status(
    "Please wait - solving global problems...", spinner="earth"
):
    do_something_important()

console.print("All fixed! :sunglasses:")

Output()

All fixed! 😎

In [3]:
console.print("[yellow]Hi[/yellow] [green underline]World")

Hi World

In [4]:
from termcolor import colored

text = colored("Hello, World!", "red")
print(text)

Hello, World!

In [5]:
import ipywidgets as widgets

from ipywidgets import IntSlider
import IPython.display as display

slider = IntSlider(value=5, min=0, max=10)
display.display(slider)

IntSlider(value=5, max=10)

In [6]:
import pandas as pd
import yfinance as yf
idk = yf.download(tickers="AAPL", interval="15m", period="1d")

[*********************100%***********************]  1 of 1 completed

In [16]:
aapl_values = []
for i in idk.iloc[:, 0:1]:
    for j in idk[i]:
        aapl_values.append(j)
print(aapl_values)

[247.82000732421875, 248.81500244140625, 248.50999450683594, 248.94009399414062, 247.61000061035156, 247.32000732421875, 248.3800048828125, 248.42999267578125, 248.63499450683594, 248.61000061035156, 249.46499633789062, 250.33999633789062, 251.77000427246094, 253.1300048828125, 253.25, 253.22500610351562, 252.58009338378906, 252.5399932861328, 252.8000030517578, 253.1300048828125, 253.39999389648438, 253.7550048828125, 253.89500427246094, 253.6699981689453, 253.9499969482422, 253.7899932861328]

In [8]:
idk.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 26 entries, 2026-03-31 13:30:00+00:00 to 2026-03-31 19:45:00+00:00
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AAPL)   26 non-null     float64
 1   (High, AAPL)    26 non-null     float64
 2   (Low, AAPL)     26 non-null     float64
 3   (Open, AAPL)    26 non-null     float64
 4   (Volume, AAPL)  26 non-null     int64
dtypes: float64(4), int64(1)
memory usage: 1.2 KB

In [9]:
idk.iloc[:, 0:1]

Price                           Close
Ticker                           AAPL
Datetime
2026-03-31 13:30:00+00:00  247.820007
2026-03-31 13:45:00+00:00  248.815002
2026-03-31 14:00:00+00:00  248.509995
2026-03-31 14:15:00+00:00  248.940094
2026-03-31 14:30:00+00:00  247.610001
2026-03-31 14:45:00+00:00  247.320007
2026-03-31 15:00:00+00:00  248.380005
2026-03-31 15:15:00+00:00  248.429993
2026-03-31 15:30:00+00:00  248.634995
2026-03-31 15:45:00+00:00  248.610001
2026-03-31 16:00:00+00:00  249.464996
2026-03-31 16:15:00+00:00  250.339996
2026-03-31 16:30:00+00:00  251.770004
2026-03-31 16:45:00+00:00  253.130005
2026-03-31 17:00:00+00:00  253.250000
2026-03-31 17:15:00+00:00  253.225006
2026-03-31 17:30:00+00:00  252.580093
2026-03-31 17:45:00+00:00  252.539993
2026-03-31 18:00:00+00:00  252.800003
2026-03-31 18:15:00+00:00  253.130005
2026-03-31 18:30:00+00:00  253.399994
2026-03-31 18:45:00+00:00  253.755005
2026-03-31 19:00:00+00:00  253.895004
2026-03-31 19:15:00+00:00  253.669998
2026-03-31 19:30:00+00:00  253.949997
2026-03-31 19:45:00+00:00  253.789993

In [18]:
idklol = yf.download(tickers="MSFT", interval="15m", period="1d")
idklol

[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume
Ticker,MSFT,MSFT,MSFT,MSFT,MSFT
Datetime,,,,,
2026-03-31 13:30:00+00:00,366.040009,367.399994,364.375000,364.630005,3485980
2026-03-31 13:45:00+00:00,367.100006,368.149994,366.070007,366.070007,1370811
2026-03-31 14:00:00+00:00,367.119995,367.529999,366.459991,367.109985,1076607
2026-03-31 14:15:00+00:00,365.450012,367.179993,365.369995,366.970001,1067324
2026-03-31 14:30:00+00:00,364.910095,365.559998,364.380005,365.460114,1343135
2026-03-31 14:45:00+00:00,363.519989,365.184998,363.070007,364.970001,2038804
2026-03-31 15:00:00+00:00,364.369995,364.519989,363.100006,363.510010,887480
2026-03-31 15:15:00+00:00,364.249786,364.899994,363.839996,364.359985,737956
2026-03-31 15:30:00+00:00,364.010010,364.744598,363.649994,364.200012,558904
2026-03-31 15:45:00+00:00,363.920013,364.799896,363.869995,364.000000,452167
2026-03-31 16:00:00+00:00,364.709991,364.989899,363.670013,363.899994,491044
2026-03-31 16:15:00+00:00,365.049988,365.149902,364.179993,364.720490,599757
2026-03-31 16:30:00+00:00,366.750000,367.989990,364.295013,365.045013,1350975
2026-03-31 16:45:00+00:00,367.964996,368.089996,366.200012,366.790009,1018961
2026-03-31 17:00:00+00:00,369.545013,369.630005,367.924988,368.009796,1973491
2026-03-31 17:15:00+00:00,368.880005,370.570007,368.665009,369.570007,1382541
2026-03-31 17:30:00+00:00,368.440002,370.149994,368.109985,368.859985,1014088
2026-03-31 17:45:00+00:00,368.350006,369.049988,368.040009,368.484985,561817
2026-03-31 18:00:00+00:00,369.549988,369.769989,368.334991,368.339996,692204
2026-03-31 18:15:00+00:00,369.846802,370.100006,369.250000,369.519989,724481
2026-03-31 18:30:00+00:00,370.489990,370.519989,369.429993,369.809998,876468
2026-03-31 18:45:00+00:00,370.529999,370.795013,370.089996,370.529999,1085911
2026-03-31 19:00:00+00:00,371.179993,371.299988,370.250000,370.510010,1287065
2026-03-31 19:15:00+00:00,371.089996,371.700012,370.730011,371.160004,1193895
2026-03-31 19:30:00+00:00,371.609985,371.700012,370.859985,371.140015,1495392
2026-03-31 19:45:00+00:00,370.160004,372.899994,369.750000,371.649994,3906030